### ISSUE TITLE
SHACL is not run automatically anymore

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/ontology#123]
Maybe something changed that pushes from within other actions don't trigger branch push triggers in other actions anymore?

```yaml
name: SHACL

on:
  workflow_dispatch:
  push:
    branches:
      - dist

jobs:
  shacl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'dist'

      - name: Build and Validate
        uses: konradhoeffner/shacl@v1
        with:
          data: all.ttl
          shacl: shacl.ttl
```
